apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This kustomization.yaml is built mirroring ../../upstream/manifests/namespace-install/kustomization.yaml.
# The differences:
# * this does not include argo server.
# * this separates cluster-scoped resources to its own folder.

bases:
- ../../base
- ../../upstream/manifests/namespace-install/workflow-controller-rbac

images:
  - name: gcr.io/ml-pipeline/workflow-controller
    newTag: v3.1.6-patch-license-compliance
    newName: deep-arena-store:5000/ml-pipeline/workflow-controller

patchesJson6902:
- target:
    version: v1
    group: apps
    kind: Deployment
    name: workflow-controller
  path: workflow-controller-deployment-patch.json
